spring.application.name=JPAP01

spring.datasource.url=jdbc:mysql://localhost:3306/jpa_demo?createDataIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Adarsh@1234$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

