spring.application.name=WeatherApp
weather.api.key=33b7782ca4194ea8982195616262504
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.forecast.url=http://api.weatherapi.com/v1/forecast.json