spring.application.name=JPA

spring.datasource.url=jdbc:mysql://localhost:3306/jpaconn
spring.datasource.username=root
spring.datasource.password=Adarsh@1234$

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true